version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: bareuni-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: bareuni
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
  #    volumes:
  #      - ./data/:/var/lib/mysql
  #      - ./db/conf.d:/etc/mysql/conf.d
  #      - ./db/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: bareuni-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: bareuni-prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:9.4.7
    container_name: bareuni-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/volume:/var/lib/grafana

#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: bareuni-spring-app
#    environment:
#      DB_URL: localhost:3306/bareuni
#      DB_USERNAME: root
#      DB_PASSWORD: root1234!
#      REDIS_HOST: localhost
#      REDIS_PORT: 6379
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#      - redis
