spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bareuni
    username: root
    password: root1234!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

---
spring.config.activate.on-profile: test

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bareuni;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
