server:
  port: 8080

spring:
  application:
    name: api
  profiles:
    group:
      "local": "db, secret, redis, security, s3, monitoring"
      "prod": "db, secret, redis, security, s3, monitoring"
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
